In [3]:
from __future__ import absolute_import, division, print_function

import tensorflow as tf

sess = tf.InteractiveSession()

In [4]:
x = [[2.]]
m = tf.matmul(x, x)
"hello, {}".format(sess.run(m))  # => "hello, [[4.]]"

'hello, [[4.]]'

In [20]:
x = tf.random_normal(dtype=tf.float32, mean=0, stddev=[3, 10, 50], shape=[3, 100, 3])

In [23]:
mean, variance = tf.nn.moments(x, axes=1)
std = tf.sqrt(variance)

In [24]:
sess.run(std)

array([[ 2.849723 ,  9.602601 , 48.144985 ],
       [ 2.9626   , 10.99742  , 52.165283 ],
       [ 3.0139637,  9.359181 , 47.651012 ]], dtype=float32)

In [55]:
# sess.run(tf.multiply(std[:, 0], std[:, 1:]))
covariance = sess.run(tf.reduce_mean(tf.matmul(tf.transpose(x, [0, 2, 1]), x), axis=1))
variance = sess.run(tf.expand_dims(std[:, 0], 1) * std[:, 1:])
covariance[1, 0]


235.95233

In [56]:
covariance

array([[  819.79095,  2492.8708 , 87181.586  ],
       [  235.95233,  4146.228  , 78950.15   ],
       [ -375.83008,  3867.7957 , 68339.06   ]], dtype=float32)

array([[ 34.978252, 173.89537 ],
       [ 30.46344 , 135.77861 ],
       [ 25.814358, 163.81622 ]], dtype=float32)